declare module '../../dto-package' {
	export const UserRole: any;
	export const UserSortColumn: any;
	export const UserLoginSchema: any;
	export const CreateUserSchema: any;
	export const UpdateUserSchema: any;
	export const UserParamSchema: any;
	export const TableSortOptionsEnum: any;
	export const TableCreateSchema: any;
	export const TableUpdatesSchema: any;
	export const TableSearchCriteriaSchema: any;
	export const TableAssignmentSchema: any;
	export const TableSchema: any;
	export const PaymentSchema: any;
	export const PaymentSearchSchema: any;
	export const PaymentSortOptions: any;
	export const RefundSchema: any;
	export const OrderSchema: any;
	export const OrderSearchSchema: any;
	export const OrderCreateSchema: any;
	export const OrderUpdateProps: any;
	export const OrderUpdateItemsSchema: any;
	export const PrepareItems: any;
	export const ReservationSchema: any;
	export const ReservationSearchCriteria: any;
	export const CreateReservationSchema: any;
	export const ReservationWithTablesSchema: any;
	export const ReservationConflict: any;
	export const ReservationDetailedSchema: any;
	export const UpdateReservationSchema: any;
	export const ReservationGuestInfoSchema: any;
	export const foodItemSchema: any;
	export const drinkItemSchema: any;
	export const createFoodItemSchema: any;
	export const createDrinkItemSchema: any;
	export const updateFoodItemSchema: any;
	export const updateDrinkItemSchema: any;
	export const searchFoodItemsSchema: any;
	export const searchDrinkItemsSchema: any;
	export const arrayQueryParamSchema: any;
	export const listPropsSchema: any;
	export const searchCriteriaSchema: any;
	export const parseQueryArray: any;
	export type UserCredentials = any;
	export type CreateUser = any;
	export type UpdateUserDto = any;
	export type UserSearchCriteria = any;
	export type UserListResult = any;
	export type UserListItem = any;
	export type CreatedUserData = any;
	export type ValidatedUserData = any;
	export type UserDto = any;
	export type TableCreate = any;
	export type TableUpdate = any;
	export type TablesList = any;
	export type TableSearchCriteria = any;
	export type TableAssignment = any;
	export type PaymentSearchCriteria = any;
	export type RefundDTO = any;
	export type OrderSearchCriteria = any;
	export type OrderCreateDTO = any;
	export type OrderFullSingleDTO = any;
	export type OrderItemExt = any;
	export type GuestItemsDTO = any;
	export type OrderItemDTO = any;
	export type ReservationDTO = any;
	export type ReservationSearchCriteriaDTO = any;
	export type CreateReservationDTO = any;
	export type ReservationWithTablesDTO = any;
	export type ReservationConflictDTO = any;
	export type ReservationDetailedDTO = any;
	export type UpdateReservationDTO = any;
	export type ReservationGuestInfo = any;
	export type SearchFoodItemsDTO = any;
	export type SearchDrinkItemsDTO = any;
	export type DrinkItemDTO = any;
	export type FoodItemDTO = any;
}