# FROM node:24-alpine

# WORKDIR /app

# # Копируем package files
# COPY package.json package-lock.json ./
# COPY tsconfig.json ./
# COPY src/dto-package ./src/dto-package
# COPY prisma ./prisma

# # Устанавливаем ALL зависимости (включая devDependencies для разработки)
# RUN npm ci

# # Копируем весь исходный код
# COPY . .

# # Генерируем Prisma клиент
# RUN npx prisma generate

# # Открываем порт
# EXPOSE 3000

# # Запускаем dev сервер с nodemon (будет смотреть за изменениями)
# CMD ["npm", "run", "dev"]
FROM node:24-alpine

# Устанавливаем pnpm
RUN npm install -g pnpm@9

WORKDIR /app

# Копируем package files
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY tsconfig.json ./
COPY prisma ./prisma

# Устанавливаем ALL зависимости (включая devDependencies для разработки)
RUN pnpm install

# Копируем весь исходный код
COPY . .

# Генерируем Prisma клиент
RUN pnpm exec prisma generate

# Открываем порт
EXPOSE 3000

# Запускаем dev сервер
CMD ["pnpm", "run", "dev"]